services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    ports:
      - "5002:5000"
    env_file:
      - ./server/.env   # ✅ important
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo_data: